name: "release-actions"

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_ADMIN_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_ADMIN_GITHUB }}
          
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          
      - name: Set RELEASE_VERSION from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=${TAG#v}" >> $GITHUB_ENV
          echo "Release version: ${TAG#v}"
        shell: bash
        
      - name: Upgrade gradle.properties
        run: sed -i "s/^version=.*/version=${RELEASE_VERSION}/g" gradle.properties
        shell: bash
        
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: true
          prWoLabels: true
          issues: true
          issuesWoLabels: true
          stripGeneratorNotice: true
          
      - name: Save version
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          push-branch: "main"
          commit-message: 'chore(release): update version to ${{ env.RELEASE_VERSION }} [skip ci]'
          force-add: "true"
          files: CHANGELOG.md gradle.properties
          name: Release Bot
          email: release-bot@bancolombia.com.co
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Publish Libraries to Maven Central
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository \
            -Pversion=${{ env.RELEASE_VERSION }} \
            -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
            -Psigning.password="${{ secrets.SIGNING_KEY_PASSWORD }}" \
            -Psigning.key="${{ secrets.SIGNING_KEY_FILE }}" \
            --no-daemon \
            --stacktrace
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SECRET_MAVEN_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SECRET_MAVEN_PASSWORD }}
